name: Build
on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish Linux
        run: dotnet publish src/UNAHUR.WorkerService/UNAHUR.WorkerService.csproj -p:PublishProfile=src/UNAHUR.WorkerService/Properties\PublishProfiles\linux-profile
      - name: Publish Windows
        run: dotnet publish src/UNAHUR.WorkerService/UNAHUR.WorkerService.csproj -p:PublishProfile=src/UNAHUR.WorkerService/Properties\PublishProfiles\win-profile
      - name: Upload Windows
        uses: actions/upload-artifact@v3
        with:
          name: UNAHUR.WorkerService.win-x64
          path: src\UNAHUR.WorkerService\bin\Release\net7.0\publish\win-x64\
      - name: Upload Linux
        uses: actions/upload-artifact@v3
        with:
          name: UNAHUR.WorkerService.linux-x64
          path: src/UNAHUR.WorkerService/bin/Release/net7.0/publish/linux-x64/