name: Build
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore dependencies
        run: dotnet restore src/UNAHUR.WorkerService/UNAHUR.WorkerService.csproj
      - name: Publish Linux
        run: dotnet publish src/UNAHUR.WorkerService/UNAHUR.WorkerService.csproj -r linux-x64 -c Release --nologo --sc true --version-suffix ${{ github.run_number }}
      - name: Upload Linux
        uses: actions/upload-artifact@v3
        with:
          name: UNAHUR.WorkerService.linux-x64
          path: src/UNAHUR.WorkerService/bin/Release/net7.0/linux-x64/publish/
      - name: Publish Windows
        run: dotnet publish src/UNAHUR.WorkerService/UNAHUR.WorkerService.csproj -r win-x64 -c Release --nologo --sc true --version-suffix ${{ github.run_number }}
      - name: Upload Windows
        uses: actions/upload-artifact@v3
        with:
          name: UNAHUR.WorkerService.win-x64
          path: src/UNAHUR.WorkerService/bin/Release/net7.0/win-x64/publish/
