name: Build
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore src/UNAHUR.SampleService.Api/UNAHUR.SampleService.Api.csproj
      - name: Publish Linux
        run: dotnet publish src/UNAHUR.SampleService.Api/UNAHUR.SampleService.Api.csproj -r linux-x64 --self-contained -c Release --nologo --sc true --version-suffix ${{ github.run_number }} /p:DebugType=None /p:DebugSymbols=false  -p:PublishSingleFile=true
      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: UNAHUR.SampleService.Api.linux-x64
          path: src/UNAHUR.SampleService.Api/bin/Release/net8.0/linux-x64/publish/
      - name: Publish Linux ARM
        run: dotnet publish src/UNAHUR.SampleService.Api/UNAHUR.SampleService.Api.csproj -r linux-arm64  --self-contained -c Release --nologo --sc true --version-suffix ${{ github.run_number }} /p:DebugType=None /p:DebugSymbols=false  -p:PublishSingleFile=true
      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: UNAHUR.SampleService.Api.linux-arm64
          path: src/UNAHUR.SampleService.Api/bin/Release/net8.0/linux-arm64/publish/
      - name: Publish Windows
        run: dotnet publish src/UNAHUR.SampleService.Api/UNAHUR.SampleService.Api.csproj -r win-x64 --self-contained -c Release --nologo --sc true --version-suffix ${{ github.run_number }} /p:DebugType=None /p:DebugSymbols=false  -p:PublishSingleFile=true
      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: UNAHUR.SampleService.Api.win-x64
          path: src/UNAHUR.SampleService.Api/bin/Release/net8.0/win-x64/publish/
