name: Build
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  release:
    types: [published]

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore src/UNAHUR.SampleService.Api/UNAHUR.SampleService.Api.csproj
      - name: Publish Linux
        run: dotnet publish src/UNAHUR.SampleService.Api/UNAHUR.SampleService.Api.csproj -o dist/linux-64  -r linux-x64 --self-contained -c Release --nologo --sc true --version-suffix ${{ github.run_number }} /p:DebugType=None /p:DebugSymbols=false  -p:PublishSingleFile=true
      - name: 'Tar files x64'
        run: tar -cvf UNAHUR.SampleService-linux-64.tar dist/linux-64
      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: UNAHUR.SampleService-linux-64.tar
      - name: Publish Linux ARM
        run: dotnet publish src/UNAHUR.SampleService.Api/UNAHUR.SampleService.Api.csproj -o dist/linux-arm64 -r linux-arm64  --self-contained -c Release --nologo --sc true --version-suffix ${{ github.run_number }} /p:DebugType=None /p:DebugSymbols=false  -p:PublishSingleFile=true
      - name: 'Tar files x64'
        run: tar -cvf UNAHUR.SampleService-linux-arm64.tar dist/linux-arm64
      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: UNAHUR.SampleService-linux-arm64.tar
  build-win:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Install WiX
        run: dotnet tool install --global wix
      - name: Restore dependencies
        run: dotnet restore src/UNAHUR.SampleService.Api/UNAHUR.SampleService.Api.csproj
      - name: Publish Windows
        run: dotnet publish src/UNAHUR.SampleService.Api/UNAHUR.SampleService.Api.csproj -o dist/win-64 -r win-x64 --self-contained -c Release --nologo --sc true --version-suffix ${{ github.run_number }} /p:DebugType=None /p:DebugSymbols=false  -p:PublishSingleFile=true
      - name: 'Tar files win x64'
        run: tar -cvf UNAHUR.SampleService-win-64.tar dist/win-64
      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: UNAHUR.SampleService-win-64.tar
      - name: Build WiX on Windows
        run: wix build .\msi.wxs -o dist/msi/UNAHUR.SampleService.msi -pdbtype none -arch x64
      - name: Upload Windows MSI
        uses: actions/upload-artifact@v4
        with:
          name: win-x64-msi
          path: dist/msi/UNAHUR.SampleService.msi
  release:
    permissions: write-all
    needs: [ build-win, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload files
        uses: AButler/upload-release-assets@v2.0
        with: 
          files: 'linux*/*.tar;win*/*.tar;win*/*.msi'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
